# Generated by Django 4.2.7 on 2023-11-15 20:54

from django.db import migrations, models
import track_my_moves.models.activity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activityType', models.CharField(choices=[('walking', 'Walking'), ('running', 'Running'), ('cycling', 'Cycling'), ('cardio', 'Cardio')], max_length=50, validators=[track_my_moves.models.activity.validate_activity_type])),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
